[build-system]
requires = ["setuptools>=75.0", "numpy>=2.0"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "Minecraft-Overviewer"
description = "Generates large resolution images of a Minecraft map."
license = "GPL-3.0-only"
requires-python = ">=3.10"
authors = [
    {name = "Andrew Brown", email = "brownan@gmail.com"},
]
urls.Homepage = "http://overviewer.org/"

readme = "README.rst"

dynamic = ["version"]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
namespaces = true
include = ["overviewer_core*"]
exclude = ["overviewer_core.src*"]
